language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source
  - if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then travis_retry composer require satooshi/php-coveralls:dev-master --no-interaction ; fi

script:
  - if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then vendor/bin/phpcs --standard=PSR2 src tests ; fi
  - if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then vendor/bin/phpmd src text unusedcode,naming,design,controversial,codesize ; fi
  - if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then vendor/bin/phpcpd src ; fi
  - if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then vendor/bin/phpunit --coverage-clover build/logs/clover.xml ; fi
  - if [[ "$TRAVIS_PHP_VERSION" != '5.6' ]]; then vendor/bin/phpunit ; fi

after_script:
  - if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then travis_retry php vendor/bin/coveralls -v ; fi
